# Generated by Django 3.2.7 on 2022-06-16 20:43

from django.db import migrations, models
import django.utils.timezone
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220616_1954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='photography',
            options={'verbose_name_plural': 'Photography'},
        ),
        migrations.AddField(
            model_name='photography',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, help_text='your picture', max_length=150, upload_to=main.models.user_dir_file),
            preserve_default=False,
        ),
    ]
